#!/bin/sh  
# \
exec oagtclsh "$0" "$@"

set auto_path [linsert $auto_path 0  /usr/local/oag/apps/lib/$env(HOST_ARCH)]
set auto_path [linsert $auto_path 0 /usr/local/oag/lib_patch/$env(HOST_ARCH)]
catch {APSStandardSetup}

set usage {usage: runJob1 -valueList <list> -tagList <list> -rootname <string> [-turns <number>]}
# E.g., runTracking -tagList "S1 S2" -valueList "1.7 5.6" -rootname run001

set valueList ""
set tagList ""
set rootname ""
set runID ""
set turns 400
set preProcessingScript ""
set postProcessingScript ""
set args $argv
if {[APSStrictParseArguments {valueList tagList rootname runID preProcessingScript postProcessingScript turns}] || ![string length $valueList] || \
	![string length $tagList] || ![string length $rootname] } {
    return -code error "$usage"
}
#puts stderr $rootname
set valueList [split $valueList " ,"]
set tagList   [split $tagList   " ,"]
if [llength $valueList]!=[llength $tagList] {
    return -code error "value and tag lists must be the same length"
}

set macroList rootname=$rootname
foreach value $valueList tag $tagList {
    lappend macroList $tag=$value
}

# Run simulation
catch {exec elegant template.ele -macro=[join $macroList ,]} result

# Copy the input settings
catch {file copy -force $rootname.inp $rootname.input} result

# Process the output

catch {exec processJob1 -rootname $rootname -valueList "$valueList" -tagList "$tagList"}  result

